worker_processes 1;
daemon off;
error_log /dev/stderr warn;
events { worker_connections 1024; }
http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile on;
  access_log /dev/stdout;
  client_max_body_size 20M;

  server {
    listen 80 default_server;
    root /var/www/html/public;
    index kese.php index.php index.html;

    location ~ /\.(env|git) { deny all; }

    location = /oferta1 {
      default_type application/vnd.openxmlformats-officedocument.wordprocessingml.document;
      add_header Content-Disposition 'attachment; filename="oferta1.docx"';
      alias /var/www/html/public/oferta1.docx;
    }

    location = /oferta2 {
      default_type application/vnd.openxmlformats-officedocument.wordprocessingml.document;
      add_header Content-Disposition 'attachment; filename="oferta2.docx"';
      alias /var/www/html/public/oferta2.docx;
    }

    location / {
      try_files $uri $uri/ /kese.php?$query_string;
    }

    location ~ \.php$ {
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
  }
}

